{
	"id": "b3affee8-04d1-11ef-8928-901b0ef714d4",
	"advisories": [
		{
			"content": {
				"id": "b3affee8-04d1-11ef-8928-901b0ef714d4",
				"title": "py-social-auth-app-django -- Improper Handling of Case Sensitivity",
				"description": "\n\t<p>GitHub Advisory Database:</p>\n\t<blockquote cite=\"https://nvd.nist.gov/vuln/detail/CVE-2024-32879\">\n\t  <p>Python Social Auth is a social authentication/registration mechanism. Prior to version 5.4.1, due to default case-insensitive collation in MySQL or MariaDB databases, third-party authentication user IDs are not case-sensitive and could cause different IDs to match. This issue has been addressed by a fix released in version 5.4.1. An immediate workaround would be to change collation of the affected field.</p>\n\t</blockquote>\n\t",
				"references": [
					{
						"source": "vuxml.freebsd.org",
						"url": "https://github.com/python-social-auth/social-app-django/security/advisories/GHSA-2gr8-3wc7-xhj3"
					},
					{
						"source": "vuxml.freebsd.org",
						"url": "https://www.vuxml.org/freebsd/b3affee8-04d1-11ef-8928-901b0ef714d4.html"
					}
				],
				"published": "2024-04-28T00:00:00Z"
			},
			"ecosystems": [
				"freebsd"
			]
		}
	],
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2024-32879",
				"references": [
					{
						"source": "vuxml.freebsd.org",
						"url": "https://www.cve.org/CVERecord?id=CVE-2024-32879"
					}
				]
			},
			"ecosystems": [
				"freebsd"
			]
		}
	],
	"detection": [
		{
			"ecosystem": "freebsd",
			"criteria": {
				"operator": "OR",
				"criterions": [
					{
						"vulnerable": true,
						"package": {
							"name": "py310-social-auth-app-django"
						},
						"affected": {
							"type": "freebsd-pkg",
							"range": [
								{
									"lt": "5.4.1"
								}
							]
						}
					},
					{
						"vulnerable": true,
						"package": {
							"name": "py311-social-auth-app-django"
						},
						"affected": {
							"type": "freebsd-pkg",
							"range": [
								{
									"lt": "5.4.1"
								}
							]
						}
					},
					{
						"vulnerable": true,
						"package": {
							"name": "py38-social-auth-app-django"
						},
						"affected": {
							"type": "freebsd-pkg",
							"range": [
								{
									"lt": "5.4.1"
								}
							]
						}
					},
					{
						"vulnerable": true,
						"package": {
							"name": "py39-social-auth-app-django"
						},
						"affected": {
							"type": "freebsd-pkg",
							"range": [
								{
									"lt": "5.4.1"
								}
							]
						}
					}
				]
			}
		}
	],
	"data_source": {
		"id": "freebsd",
		"raws": [
			"vuls-data-raw-freebsd/b3affee8-04d1-11ef-8928-901b0ef714d4.json"
		]
	}
}
